#!/usr/bin/env python3
"""Generate sw.js with a CONTENT-HASH cache name and network-first fetch.

OncOS PWA rule: version the service-worker cache by content hash (not date)
and serve network-first, so clients never get stuck on stale content. Run this
whenever app files change (deploy.sh calls it). Re-running with no file change
produces an identical sw.js (no spurious churn)."""
import hashlib
import pathlib

HERE = pathlib.Path(__file__).parent
# Files whose content determines the cache version. Order matters for the hash.
ASSETS = [
    "index.html", "drugs.js", "manifest.webmanifest",
    "icon-192.png", "icon-512.png", "icon-maskable-512.png", "apple-touch-icon-180.png",
]

h = hashlib.sha256()
for name in ASSETS:
    p = HERE / name
    if p.exists():
        h.update(p.read_bytes())
ver = h.hexdigest()[:12]

asset_list = ",\n  ".join(f"'./{a}'" for a in (["./"] + ASSETS))

sw = f"""/* Generated by make_sw.py — do not hand-edit.
 * Cache name is a content hash of the app files, so each real change ships a
 * fresh cache. Fetch is NETWORK-FIRST: try the network, fall back to cache
 * offline. This is the OncOS PWA rule — never date-versioned cache-first. */
const CACHE = 'oncos-systemic-{ver}';
const ASSETS = [
  {asset_list}
];

self.addEventListener('install', (e) => {{
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
}});

self.addEventListener('activate', (e) => {{
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
}});

self.addEventListener('fetch', (e) => {{
  if (e.request.method !== 'GET') return;
  e.respondWith(
    fetch(e.request)
      .then((resp) => {{
        const copy = resp.clone();
        caches.open(CACHE).then((c) => c.put(e.request, copy)).catch(() => {{}});
        return resp;
      }})
      .catch(() => caches.match(e.request).then((hit) => hit || caches.match('./index.html')))
  );
}});
"""

out = HERE / "sw.js"
out.write_text(sw, encoding="utf-8")
print(f"wrote sw.js  (cache oncos-systemic-{ver})")
